# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mailto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='warnlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=50)),
                ('warndate', models.DateField()),
            ],
        ),
    ]
