# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-05 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='systemdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.CharField(max_length=50, null=True)),
                ('publickeydaystart', models.DateField(null=True)),
                ('publickeydaystop', models.DateField(null=True)),
                ('privatekeydaystart', models.DateField(null=True)),
                ('privatekeydaystop', models.DateField(null=True)),
                ('publicgain', models.CharField(max_length=50, null=True)),
                ('privategain', models.CharField(max_length=50, null=True)),
                ('update', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='systeminfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='systemdetail',
            name='sysid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certhome.systeminfo'),
        ),
    ]
