# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certhome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemdetail',
            name='sysid',
        ),
        migrations.AddField(
            model_name='systemdetail',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='systemdetail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='systeminfo',
        ),
    ]
